#!/usr/bin/env python3

from sys import agrv as a

progname = a[0].split('/')[-1]


def print_usage():
    print(f'{progname} [options] [fileprefix ...]')
    exit(1)

if len(a) == 1:
    print_usage()

fileprefixes = []
react = ''

for arg in a:
    if arg[0] == '-':
        if arg in ['-r', '--react']:
            react = '<react></react>'
        else:
            print("unknown option usage {arg}")
            print_usage()
    else:
        fileprefixes.append(arg)


html = f'''
<!DOCTYPE html>
<html>
<head>
<head>
<body>
</body>
{react}
</html>
'''

for file in fileprefixes:
    open(fileprefixe + '.html', 'w').write(html)
